import requests

response =requests.get(
    "http://rewizor-api.ngrok.dev/documents",
    headers={"x-api-key": "rida_Wmw3xVlImfAoaiTzeTb6zRtOoyGrSWXAekXR5Shap0iRAbHtwr0MnpKQ6gjh4I37"}
) 

print(response.json()) 

# [
#   {
#     'dkr_Id': 12783,
#     'dkr_IdRoku': 1,
#     'dkr_DataDekretacji': '2026-03-23T00: 00: 00',
#     'dkr_DataDokumentu': '2026-03-23T00: 00: 00',
#     'dkr_DataOperacji': '2026-03-23T00: 00: 00',
#     'dkr_Status': 1,
#     'dkr_Rejestr': 'RSO',
#     'dkr_Numer': 11474,
#     'dkr_NrPelny': 'RSO-11474',
#     'dkr_DokumentZrodlowy': 'FS10794/2026',
#     'dkr_KontrolaBilansowania': True,
#     'dkr_Waluta': 'EUR',
#     'dkr_WalutaWyswietlana': 'EUR',
#     'dkr_KursDokumentu': 4.2768,
#     'dkr_LiczbaJednostek': 1,
#     'dkr_RodzajKursu': 1,
#     'dkr_DataKursu': '2026-03-20T00: 00: 00',
#     'dkr_IdBanku': 1,
#     'dkr_Kwota': 4554.75,
#     'dkr_KwotaWaluta': 1064.99,
#     'dkr_Uwagi': "Utworzono na podst. schematu imp. 'FSschematstandardowy'",
#     'dkr_IdKategorii': 0,
#     'dkr_Dekretowal': 'DN',
#     'dkr_Ksiegowal': '',
#     'dkr_TypObiektu': 0,
#     'dkr_IdObiektu': 0,
#     'dkr_TypDokImport': 131072,
#     'dkr_IdDokImport': 5500034,
#     'dkr_ImportPochodzenie': 1,
#     'dkr_IdKh': 0,
#     'dkr_SymbolKh': '',
#     'dkr_NrWDzienniku': 0,
#     'dkr_Podtyp': 0,
#     'dkr_TrybWprowadzaniaRozrachunkow': 4,
#     'dkr_WalutaKursWyswietlany': 4.2768,
#     'dkr_KwotaWn': 4554.75,
#     'dkr_KwotaMa': 4554.75,
#     'dkr_KwotaWalutaWn': 1064.99,
#     'dkr_KwotaWalutaMa': 1064.99,
#     'dkr_Storno': False,
#     'dkr_Opis': 'FSFakturasprzedaży',
#     'dkr_RodzajDowodu': 1,
#     'dkr_IdObiektuVatOss': 0,
#     'dkr_NumerKSeF': '',
#     'dkr_CzyWymagaZatwierdzeniaKursuZEFaktury': False,
#     'kat_Id': 0,
#     'kat_Nazwa': '',
#     'kat_Typ': 0,
#     'kat_Podtytul': '',
#     'rdk_Id': 1,
#     'rdk_Nazwa': 'Fakturasprzedaży',
#     'rdk_TypWartosci': 131072,
#     'positionCount': 0,
#     'totalDebitAmount': 0,
#     'totalCreditAmount': 0
#   },
#   {
#     'dkr_Id': 12784,
#     'dkr_IdRoku': 1,
#     'dkr_DataDekretacji': '2026-03-23T00: 00: 00',
#     'dkr_DataDokumentu': '2026-03-23T00: 00: 00',
#     'dkr_DataOperacji': '2026-03-23T00: 00: 00',
#     'dkr_Status': 1,
#     'dkr_Rejestr': 'RSO',
#     'dkr_Numer': 11475,
#     'dkr_NrPelny': 'RSO-11475',
#     'dkr_DokumentZrodlowy': 'FS10795/2026',
#     'dkr_KontrolaBilansowania': True,
#     'dkr_Waluta': 'EUR',
#     'dkr_WalutaWyswietlana': 'EUR',
#     'dkr_KursDokumentu': 4.2768,
#     'dkr_LiczbaJednostek': 1,
#     'dkr_RodzajKursu': 1,
#     'dkr_DataKursu': '2026-03-20T00: 00: 00',
#     'dkr_IdBanku': 1,
#     'dkr_Kwota': 2117.02,
#     'dkr_KwotaWaluta': 495.0,
#     'dkr_Uwagi': "Utworzono na podst. schematu imp. 'FSschematstandardowy'",
#     'dkr_IdKategorii': 0,
#     'dkr_Dekretowal': 'DN',
#     'dkr_Ksiegowal': '',
#     'dkr_TypObiektu': 0,
#     'dkr_IdObiektu': 0,
#     'dkr_TypDokImport': 131072,
#     'dkr_IdDokImport': 5500042,
#     'dkr_ImportPochodzenie': 1,
#     'dkr_IdKh': 0,
#     'dkr_SymbolKh': '',
#     'dkr_NrWDzienniku': 0,
#     'dkr_Podtyp': 0,
#     'dkr_TrybWprowadzaniaRozrachunkow': 4,
#     'dkr_WalutaKursWyswietlany': 4.2768,
#     'dkr_KwotaWn': 2117.02,
#     'dkr_KwotaMa': 2117.02,
#     'dkr_KwotaWalutaWn': 495.0,
#     'dkr_KwotaWalutaMa': 495.0,
#     'dkr_Storno': False,
#     'dkr_Opis': 'FSFakturasprzedaży',
#     'dkr_RodzajDowodu': 1,
#     'dkr_IdObiektuVatOss': 0,
#     'dkr_NumerKSeF': '',
#     'dkr_CzyWymagaZatwierdzeniaKursuZEFaktury': False,
#     'kat_Id': 0,
#     'kat_Nazwa': '',
#     'kat_Typ': 0,
#     'kat_Podtytul': '',
#     'rdk_Id': 1,
#     'rdk_Nazwa': 'Fakturasprzedaży',
#     'rdk_TypWartosci': 131072,
#     'positionCount': 0,
#     'totalDebitAmount': 0,
#     'totalCreditAmount': 0
#   }
# ]
